### ISSUE TITLE
Trained Model file

### ISSUE THREAD

**Issue by chetan1836** [Mukilan-Krishnakumar/Custom_YOLOv8_Object_Track#1]
Can you provide a trained model file.

**Comment by Mukilan-Krishnakumar** [comment]
Hi @chetan1836, sorry for such a late reply. As we trained on scraped images, I am not supposed to make the model file available. Hope you understand.

**Comment by chetan1836** [comment]
Thanks for your response. If you don't want to share it in public I'll DM my email if that's ok.
