### ISSUE TITLE
A issue in step 4 in YOLOv8 tutorial

### ISSUE THREAD

**Issue by Streeb30** [Mukilan-Krishnakumar/Custom_YOLOv8_Object_Track#2]
Got one issue in step 4:
(yolo_env) qisenskaist@standard-vm-img-lewis:~/Custom_YOLOv8_Object_Track/4_Custom_Train_YOLOv8$ python3 train_yolov8n.py
Traceback (most recent call last):
  File "train_yolov8n.py", line 3, in <module>
    from wandb.integration.yolov8 import add_callbacks as add_wandb_callbacks
ModuleNotFoundError: No module named 'wandb'

**Comment by Mukilan-Krishnakumar** [comment]
Hey @Streeb30 
Activate your `yolo_env` and run the following command:
```bash
pip install wandb
```

Happy Coding!!
